/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as CapitalRouteImport } from './routes/capital'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as FoundationRouteImport } from './routes/foundation'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as IgxAiRouteImport } from './routes/igx-ai'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MediaRouteImport } from './routes/media'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VaultRouteImport } from './routes/vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalRoute = CapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationRoute = FoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const IgxAiRoute = IgxAiRouteImport.update({
  id: '/igx-ai',
  path: '/igx-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/capital': typeof CapitalRoute
  '/console': typeof ConsoleRoute
  '/directory': typeof DirectoryRoute
  '/ecosystem': typeof EcosystemRoute
  '/foundation': typeof FoundationRoute
  '/governance': typeof GovernanceRoute
  '/igx-ai': typeof IgxAiRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/proposals': typeof ProposalsRoute
  '/settings': typeof SettingsRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/capital': typeof CapitalRoute
  '/console': typeof ConsoleRoute
  '/directory': typeof DirectoryRoute
  '/ecosystem': typeof EcosystemRoute
  '/foundation': typeof FoundationRoute
  '/governance': typeof GovernanceRoute
  '/igx-ai': typeof IgxAiRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/proposals': typeof ProposalsRoute
  '/settings': typeof SettingsRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/capital': typeof CapitalRoute
  '/console': typeof ConsoleRoute
  '/directory': typeof DirectoryRoute
  '/ecosystem': typeof EcosystemRoute
  '/foundation': typeof FoundationRoute
  '/governance': typeof GovernanceRoute
  '/igx-ai': typeof IgxAiRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/proposals': typeof ProposalsRoute
  '/settings': typeof SettingsRoute
  '/vault': typeof VaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/capital'
    | '/console'
    | '/directory'
    | '/ecosystem'
    | '/foundation'
    | '/governance'
    | '/igx-ai'
    | '/login'
    | '/media'
    | '/proposals'
    | '/settings'
    | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/capital'
    | '/console'
    | '/directory'
    | '/ecosystem'
    | '/foundation'
    | '/governance'
    | '/igx-ai'
    | '/login'
    | '/media'
    | '/proposals'
    | '/settings'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/capital'
    | '/console'
    | '/directory'
    | '/ecosystem'
    | '/foundation'
    | '/governance'
    | '/igx-ai'
    | '/login'
    | '/media'
    | '/proposals'
    | '/settings'
    | '/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  CapitalRoute: typeof CapitalRoute
  ConsoleRoute: typeof ConsoleRoute
  DirectoryRoute: typeof DirectoryRoute
  EcosystemRoute: typeof EcosystemRoute
  FoundationRoute: typeof FoundationRoute
  GovernanceRoute: typeof GovernanceRoute
  IgxAiRoute: typeof IgxAiRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  ProposalsRoute: typeof ProposalsRoute
  SettingsRoute: typeof SettingsRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital': {
      id: '/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof CapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation': {
      id: '/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof FoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igx-ai': {
      id: '/igx-ai'
      path: '/igx-ai'
      fullPath: '/igx-ai'
      preLoaderRoute: typeof IgxAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  CapitalRoute: CapitalRoute,
  ConsoleRoute: ConsoleRoute,
  DirectoryRoute: DirectoryRoute,
  EcosystemRoute: EcosystemRoute,
  FoundationRoute: FoundationRoute,
  GovernanceRoute: GovernanceRoute,
  IgxAiRoute: IgxAiRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  ProposalsRoute: ProposalsRoute,
  SettingsRoute: SettingsRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
